kind: Service
apiVersion: v1
metadata:
  name: hiking-api
  labels:
    app: hiking-api
spec:
  type: NodePort
  selector:
    app: hiking-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiking-api
  labels:
    app: hiking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiking-api
  template:
    metadata:
      labels:
        app: hiking-api
    spec:
      imagePullSecrets:
        - name: svlassiev-dockerhub
      containers:
        - name: hiking-api
          image: svlassiev/hiking-api:20.03.31
          imagePullPolicy: Always
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongo-cdc-0.mongo-cdc:27017"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/firebase/firebase-service-account.json"
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: firebase
                  key: adminEmail
            - name: FIREBASE_URL
              valueFrom:
                secretKeyRef:
                  name: firebase
                  key: databaseUrl
            - name: PORT
              value: "9090"
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 100m
              memory: 2560M
          volumeMounts:
            - name: firebase-service-account
              mountPath: /firebase
      volumes:
        - name: firebase-service-account
          secret:
            secretName: firebase-service-account