kind: Service
apiVersion: v1
metadata:
  name: hiking-api
  labels:
    app: hiking-api
spec:
  type: NodePort
  selector:
    app: hiking-api
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiking-api
  labels:
    app: hiking-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiking-api
  template:
    metadata:
      labels:
        app: hiking-api
    spec:
      imagePullSecrets:
        - name: svlassiev-dockerhub
      containers:
        - name: hiking-api
          image: svlassiev/hiking-api:19.10.18
          imagePullPolicy: Always
          env:
            - name: MONGO_CONNECTION_STRING
              value: "mongo-cdc-0.mongo-cdc:27017"
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 100m
              memory: 2560M